/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * displayform.java
 *
 * Created on 5 Dec, 2013, 7:25:31 PM
 */

/**
 *
 * @author hp
 */
import javax.swing.JOptionPane;
 import java.sql.*;
 import javax.swing.table.*;
public class displayform extends javax.swing.JFrame {

    /** Creates new form displayform */
    public displayform() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TABLE = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        jLabel1.setText("jLabel1");

        jButton2.setText("jButton2");

        jButton4.setText("jButton4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TABLE.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        TABLE.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        TABLE.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Vis_Id", "Name", "Address", "Nationality", "Age", "Phone_No", "Email", "Room No", "Total Amount"
            }
        ));
        TABLE.setGridColor(new java.awt.Color(0, 0, 0));
        TABLE.setOpaque(false);
        jScrollPane1.setViewportView(TABLE);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 101, 760, 233));

        jLabel2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(372, 22, 175, -1));

        jButton3.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12));
        jButton3.setText("DISPLAY ALL RECORDS");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(551, 15, -1, -1));

        jButton5.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12));
        jButton5.setText("HOME");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(615, 58, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Nubia-Hotel-Reception.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 760, 360));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    DefaultTableModel dm=(DefaultTableModel)TABLE.getModel();
      TABLE.setVisible(true);
      int rows=dm.getRowCount();
      if(rows>0)
      {
         for(int i=0;i<rows;i++)
          dm.removeRow(0); //to clear the existing table
      }


        try
    {
        Class.forName("java.sql.Driver");
        Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/hotel_management", "root", "root");
        Statement  stmt=null;
        stmt=con.createStatement();
        String query1="Select * from visitors";
       ResultSet rs=stmt.executeQuery(query1);
       while(rs.next())
       {
           int id=rs.getInt("Vis_id");
           String nm=rs.getString("Name");
           String add=rs.getString("Address");
           String nat=rs.getString("Nationality");
           String age=rs.getString("Age");
           String phone=rs.getString("Phone_No");
           String email=rs.getString("Email");
           String room=rs.getString("Room_No");
           double amt=rs.getDouble("Bill");
           dm.addRow(new Object[]{id,nm,add,nat,age,phone,email,room,amt});
       }

    }catch(Exception e)
    {
            JOptionPane.showMessageDialog(null,e.getMessage());
        }     
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
new visitor_management().setVisible(true);  dispose();        
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new displayform().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TABLE;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

}
