/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
import javax.swing.*;
import java.sql.*;
/*
 * login.java
 *
 * Created on Nov 19, 2013, 10:26:24 AM
 */
/**
 *
 * @author Sejal Varshney
 */
public class login extends javax.swing.JFrame {

    /** Creates new form login */
    public login() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        password = new javax.swing.JPasswordField();
        username = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe Print", 1, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("LOGIN");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 90, 30));

        jLabel4.setFont(new java.awt.Font("Segoe Print", 1, 13)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("ID:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, -1, 20));

        jLabel5.setFont(new java.awt.Font("Segoe Print", 1, 13)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Password:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, -1, -1));

        jButton1.setFont(new java.awt.Font("Segoe Print", 0, 13)); // NOI18N
        jButton1.setText("Login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, -1, -1));

        password.setFont(new java.awt.Font("Segoe Print", 0, 13)); // NOI18N
        password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordActionPerformed(evt);
            }
        });
        getContentPane().add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, 120, -1));

        username.setFont(new java.awt.Font("Segoe Print", 0, 13)); // NOI18N
        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });
        getContentPane().add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 120, -1));

        jLabel3.setFont(new java.awt.Font("French Script MT", 3, 48));
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Bellagio..");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, 170, 70));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-220, 0, 680, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
if(username.getText().equalsIgnoreCase("sejal")&&password.getText().equals("sejal"))
        {
        
            try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mysql?zeroDateTimeBehavior=convertToNull", "root", "root");
            Statement stmt = con.createStatement();
            String query="Create Database if not exists hotel_management; ";
            stmt.execute(query);
                    try{
                        String query1 = "use hotel_management;";
                        stmt.execute(query1);
                    }
                     catch(Exception e){
                            JOptionPane.showMessageDialog(null,e.getMessage());
                        }   
                    try{
                            String query2 ="create table if not exists visitors("+
                            "Vis_id Integer Primary Key Auto_increment,"+
                            "Name Varchar(40),"+
                            "Address Varchar(80),"+
                            "Nationality Varchar(20),"+
                            "Age VARCHAR(14),"+
                            "Phone_No Varchar(20),"+
                            "Email Varchar(40),"+
                            "Room_No char(14),"+
                            "Nights VARCHAR(14),"+
                            "Guests VARCHAR(14),"+
                            "Amount VARCHAR(10),"+
                            "Bill VARCHAR(10))";
                            stmt.execute(query2);
                        }
                    catch(Exception e){
                            JOptionPane.showMessageDialog(null,e.getMessage());
                        }
                   try{
                            String query3 ="create table if not exists room("+
                            "Room_No char(14),"+
                            "Availability char(20));";
                            stmt.execute(query3);
                            String qry1= "INSERT INTO room VALUES('F1','available');";
                            stmt.executeUpdate(qry1);
                            String qry2= "INSERT INTO room VALUES('F2','available');";
                            stmt.executeUpdate(qry2);
                            String qry3= "INSERT INTO room VALUES('F3','available');";
                            stmt.executeUpdate(qry3);
                            String qry4= "INSERT INTO room VALUES('F4','available');";
                            stmt.executeUpdate(qry4);
                            String qry5= "INSERT INTO room VALUES('R1','available');";
                            stmt.executeUpdate(qry5);
                            String qry6= "INSERT INTO room VALUES('R2','available');";
                            stmt.executeUpdate(qry6);
                            String qry7= "INSERT INTO room VALUES('R3','available');";
                            stmt.executeUpdate(qry7);
                            String qry8= "INSERT INTO room VALUES('R4','available');";
                            stmt.executeUpdate(qry8);
                            String qry9= "INSERT INTO room VALUES('P1','available');";
                            stmt.executeUpdate(qry9);
                            String qry10= "INSERT INTO room VALUES('P2','available');";
                            stmt.executeUpdate(qry10);
                            String qry11= "INSERT INTO room VALUES('P3','available');";
                            stmt.executeUpdate(qry11);
                            String qry12= "INSERT INTO room VALUES('P4','available');";
                            stmt.executeUpdate(qry12);
                   }
                   catch(Exception e){
                            JOptionPane.showMessageDialog(null,e.getMessage());
                            }
                   
                   visitor_management v =new visitor_management();
                   v.setVisible(true);
                   dispose();
            }
             catch(Exception e) {
             JOptionPane.showMessageDialog(null,e.getMessage());
             }
            
     }               
    else JOptionPane.showMessageDialog(null,"Sorry invalid password");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        
    }//GEN-LAST:event_usernameActionPerformed

    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordActionPerformed
       
    }//GEN-LAST:event_passwordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new login().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPasswordField password;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
