import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * search_record.java
 *
 * Created on Dec 18, 2013, 9:21:31 PM
 */
/**
 *
 * @author Sejal Varshney
 */
public class search_record extends javax.swing.JFrame {

    /** Creates new form search_record */
    public search_record() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        hottable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        scb = new javax.swing.JComboBox();
        ocb = new javax.swing.JComboBox();
        criteriatf = new javax.swing.JTextField();
        emptyBtn = new javax.swing.JButton();
        searchBtn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        hottable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Vis_No", "Name", "Phone_No", "Email", "Room_No", "Nights", "Guests", "Net Amount", "Total Amount"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        hottable.setEditingColumn(0);
        hottable.setEditingRow(0);
        jScrollPane1.setViewportView(hottable);
        hottable.getColumnModel().getColumn(2).setResizable(false);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 750, 200));

        jLabel1.setText("SEARCH FIELD");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        jLabel2.setText("CRITERIA");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, -1, -1));

        scb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Vis_id", "Name", "Room_No", "Total Amount" }));
        scb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scbActionPerformed(evt);
            }
        });
        getContentPane().add(scb, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        ocb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "=", "<", ">", "!=" }));
        getContentPane().add(ocb, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, -1, -1));
        getContentPane().add(criteriatf, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 112, -1));

        emptyBtn.setText("EMPTY TABLE");
        emptyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emptyBtnActionPerformed(evt);
            }
        });
        getContentPane().add(emptyBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 20, 120, 30));

        searchBtn.setText("SEARCH");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });
        getContentPane().add(searchBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 60, 120, 30));

        jButton1.setText("HOME");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 100, 120, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Incredible-Bellagio-Fountains-in-Las-Vegas-5.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-430, 0, 1190, 1020));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void emptyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emptyBtnActionPerformed
      DefaultTableModel model=(DefaultTableModel) hottable.getModel();
      int rows= model.getRowCount();
      if(rows>0){
          for(int i=0;i<rows;i++)
              model.removeRow(0);
                }
      
    }//GEN-LAST:event_emptyBtnActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        emptyBtn.doClick();
        DefaultTableModel model=(DefaultTableModel) hottable.getModel();
        int r= model.getRowCount();
        for(int i=0;i<r;i++)
            model.removeRow(r);
        
        
        String query1;
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hotel_management", "root", "root");
            Statement stmt = con.createStatement();
            String ofld=(String) ocb.getSelectedItem();
            String sfld=(String) scb.getSelectedItem();
            String crit= criteriatf.getText();
            if(scb.getSelectedIndex()==0)
              query1="SELECT Vis_id,Name,Phone_No,Email,Room_No,Nights,Guests,Amount,Bill FROM visitors WHERE Vis_id"+ocb.getSelectedItem().toString()+""+(crit)+" ;";
            
            else {query1="SELECT Vis_id,Name,Phone_No,Email,Room_No,Nights,Guests,Amount,Bill FROM visitors WHERE "+scb.getSelectedItem().toString()+ocb.getSelectedItem().toString()+"'"+(crit)+"' ;";}
            ResultSet rs=stmt.executeQuery(query1);
           
            while(rs.next()){
                model.addRow(new Object[]{
                rs.getInt(1),rs.getString("Name"),rs.getString("Phone_No"),rs.getString("Email"),rs.getString("Room_No"),rs.getString("Nights"),rs.getString("Guests"),rs.getString("Amount"),rs.getString("Bill")});
            }
          
        }
        catch(Exception e){
                            JOptionPane.showMessageDialog(null,e.getMessage());
                        }   
    }//GEN-LAST:event_searchBtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
new visitor_management().setVisible(true);
       dispose();      
    }//GEN-LAST:event_jButton1ActionPerformed

    private void scbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_scbActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(search_record.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(search_record.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(search_record.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(search_record.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new search_record().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField criteriatf;
    private javax.swing.JButton emptyBtn;
    private javax.swing.JTable hottable;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox ocb;
    private javax.swing.JComboBox scb;
    private javax.swing.JButton searchBtn;
    // End of variables declaration//GEN-END:variables
}
